version: "3.3"
services:
  nginx:
    image: steer/tracker_nginx:latest
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
    networks:
      - steer
    deploy:
      replicas: 3
  app:
    image: steer/tracker_app
    networks:
      - steer
    deploy:
      replicas: 3
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production
  redis:
    image: redis
    networks:
      - steer
    deploy:
      replicas: 3
networks:
  steer:
    external: true